# Generated by Django 5.1.7 on 2025-03-15 17:59

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FileMetadata',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file_name', models.CharField(max_length=255)),
                ('file_url', models.CharField(blank=True, max_length=255, null=True)),
                ('file_size', models.IntegerField(blank=True, null=True)),
                ('content_type', models.CharField(blank=True, max_length=255, null=True)),
                ('etag', models.CharField(blank=True, max_length=255, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('total_chunks', models.IntegerField(default=0)),
                ('checksum', models.CharField(blank=True, max_length=64)),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='core_files', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='FileChunk',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('chunk_index', models.IntegerField()),
                ('chunk_file', models.CharField(blank=True, max_length=255, null=True)),
                ('chunk_size', models.IntegerField(blank=True, null=True)),
                ('etag', models.CharField(blank=True, max_length=255, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('file_metadata', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='core.filemetadata')),
            ],
            options={
                'ordering': ['chunk_index'],
            },
        ),
        migrations.AddIndex(
            model_name='filemetadata',
            index=models.Index(fields=['-uploaded_at'], name='core_fileme_uploade_b202f7_idx'),
        ),
        migrations.AddIndex(
            model_name='filemetadata',
            index=models.Index(fields=['uploaded_by', '-uploaded_at'], name='core_fileme_uploade_2e1833_idx'),
        ),
        migrations.AddIndex(
            model_name='filechunk',
            index=models.Index(fields=['file_metadata', 'chunk_index'], name='core_filech_file_me_e29eee_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='filechunk',
            unique_together={('file_metadata', 'chunk_index')},
        ),
    ]
