POST http://127.0.0.1:8000/api/signup
Content-Type: application/json

{ "username": "test", "password": "123!", "email": "adam@mail.com" }

###

POST http://127.0.0.1:8000/api/login
Content-Type: application/json

{ "username": "admin", "password": "123!" }

###

GET http://127.0.0.1:8000/api/test_token
Content-Type: application/json
Authorization: token be0f7de3fe40d631b0b6f55dd5ba0496399778e1

###
POST http://127.0.0.1:8000/api/upload/
Content-Type: multipart/form-data; boundary=boundary
Authorization: token be0f7de3fe40d631b0b6f55dd5ba0496399778e1

--boundary
Content-Disposition: form-data; name="image_file"; filename="test_upload.png"
Content-Type: image/png

< test_upload.png
--boundary

###

GET http://127.0.0.1:8000/api/storage/
Content-Type: application/json
Authorization: token be0f7de3fe40d631b0b6f55dd5ba0496399778e1


###

DELETE http://127.0.0.1:8000/api/delete/982c33f7-e734-11ef-a2dd-4c1d9632fe19/
Content-Type: application/json
Authorization: token be0f7de3fe40d631b0b6f55dd5ba0496399778e1


###

GET http://127.0.0.1:8000/api/storage/
Content-Type: application/json
Authorization: token be0f7de3fe40d631b0b6f55dd5ba0496399778e1
