# Generated by Django 4.2.20 on 2025-03-12 23:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FileMetadata',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file_name', models.CharField(max_length=255)),
                ('file_url', models.CharField(blank=True, max_length=255, null=True)),
                ('file_size', models.IntegerField(blank=True, null=True)),
                ('content_type', models.CharField(blank=True, max_length=255, null=True)),
                ('etag', models.CharField(blank=True, max_length=255, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('total_chunks', models.IntegerField(default=0)),
                ('checksum', models.CharField(blank=True, max_length=64)),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FileChunk',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('chunk_index', models.IntegerField()),
                ('chunk_file', models.CharField(blank=True, max_length=255, null=True)),
                ('chunk_size', models.IntegerField(blank=True, null=True)),
                ('etag', models.CharField(blank=True, max_length=255, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('file_metadata', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='upload.filemetadata')),
            ],
            options={
                'unique_together': {('file_metadata', 'chunk_index')},
            },
        ),
    ]
