# Generated by Django 5.1.7 on 2025-03-15 17:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0002_fileaccesslog'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fileaccesslog',
            name='user',
        ),
        migrations.AlterModelOptions(
            name='filechunk',
            options={'ordering': ['chunk_index']},
        ),
        migrations.AlterModelOptions(
            name='filemetadata',
            options={'ordering': ['-uploaded_at']},
        ),
        migrations.AddIndex(
            model_name='filechunk',
            index=models.Index(fields=['file_metadata', 'chunk_index'], name='upload_file_file_me_495e93_idx'),
        ),
        migrations.AddIndex(
            model_name='filemetadata',
            index=models.Index(fields=['-uploaded_at'], name='upload_file_uploade_2151a3_idx'),
        ),
        migrations.AddIndex(
            model_name='filemetadata',
            index=models.Index(fields=['uploaded_by', '-uploaded_at'], name='upload_file_uploade_4f92ab_idx'),
        ),
        migrations.DeleteModel(
            name='FileAccessLog',
        ),
    ]
