# Generated by Django 5.1.7 on 2025-03-15 17:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FileAccessLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=255)),
                ('action', models.CharField(choices=[('UPLOAD', 'Upload'), ('DOWNLOAD', 'Download'), ('DELETE', 'Delete'), ('VIEW', 'View Details')], max_length=10)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='monitored_file_accesses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['-timestamp'], name='monitoring__timesta_acb559_idx'), models.Index(fields=['user', '-timestamp'], name='monitoring__user_id_fb3ca8_idx'), models.Index(fields=['action', '-timestamp'], name='monitoring__action_954743_idx')],
            },
        ),
    ]
